# 服务端口
server:
  port: 8080

spring:
  # 只需配置 datasource 就可在程序中注入 JdbcTemplate
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    #mycat分片数据库端口默认为8066
    #url: jdbc:mysql://127.0.0.1:8066/TESTDB?characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    #username: test
    #password: test

    url: jdbc:mysql://192.168.1.73:3306/gdws_cpos_server_3.2?characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

  redis:
#    host: 192.168.1.73
#    password: admin@123
    host: 10.211.55.4
#    port: 6379
#    timeout: 3s
#    database: 0

    # 哨兵
    sentinel:
      host1: 172.20.1.230
      port1: 26379

      host2: 172.20.1.231
      port2: 26379

      host3: 172.20.1.232
      port3: 26379

    # 集群
    cluster:
      host1: 172.20.1.230
      port1: 26379

      host2: 172.20.1.231
      port2: 26379

      host3: 172.20.1.232
      port3: 26379