spring:
  redis:
#    host: 192.168.1.73
#    password: admin@123
    host: 10.211.55.4
    port: 6379
    timeout: 3s
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 500
