/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jd_JNI_HelloWorld */

#ifndef _Included_cn_jd_JNI_HelloWorld
#define _Included_cn_jd_JNI_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jd_JNI_HelloWorld
 * Method:    cMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_jd_JNI_HelloWorld_cMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
